// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe7dsr4TYIDqpDi-hP9-I0WswY1dQTA3A',
    appId: '1:590696884197:web:fb751eb55d168f5c76f10c',
    messagingSenderId: '590696884197',
    projectId: 'test-app-a4b62',
    authDomain: 'test-app-a4b62.firebaseapp.com',
    storageBucket: 'test-app-a4b62.firebasestorage.app',
    measurementId: 'G-FWLDT91VE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5PzLcOnQv7J8taQHm7ynHMhUgLoRD64',
    appId: '1:590696884197:android:272f77647761cb5676f10c',
    messagingSenderId: '590696884197',
    projectId: 'test-app-a4b62',
    storageBucket: 'test-app-a4b62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGibKMY5LYYSA73N3QsZGazQ0nZ1tshXU',
    appId: '1:590696884197:ios:eb328de8d43aacde76f10c',
    messagingSenderId: '590696884197',
    projectId: 'test-app-a4b62',
    storageBucket: 'test-app-a4b62.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );
}
